# to comile the all three codes together type 'make' on the compiler, then it would create an objective file 'main', now to execute this file type './main' it would show the combined output of all the codes

all: 
		gcc Malloc_main.c -lm Malloc_function.c -lm -o main
